spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/baby_guess?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: mysql123
    schema:
      classpath: schema.sql
    sql-script-encoding: utf-8
    initialization-mode: always

server:
  port: 8080
mybatis:
  typeAliasesPackage: com.example.demo.model
  mapperLocations: classpath:mapper/*.xml
